version: "3"

networks:
  laravel:
    driver: bridge

services:
  nginx:
    image: library/nginx:stable-alpine
    container_name: nginx-laravel
    volumes:
      -  ./src/app:/var/www/html
      -  ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      -  "8080:80"
    depends_on:
      -  php
      -  mysql
    networks:
      -  laravel

  mysql:
    image: library/mysql:5.7.22
    container_name: mysql-laravel
    ports:
      -  "3307:3306"
    restart: unless-stopped
    volumes:
      -  ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: lemp
      MYSQL_USER:  root
      MYSQL_PASSWORD: password
      MYSQL_TAGS: dev
      MYSQL_ROOT_PASSWORD: password
      SERVICE_NAME: mysql
    networks:
      -  laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-laravel
    working_dir:  /var/www/html
    restart:  unless-stopped
    volumes:
      -  ./src/app:/var/www/html
    ports:
      -  "9000:9000"
    networks:
      -  laravel



